export const INJECTION_TOKENS = {
  EMAIL_PROVIDER: 'EMAIL_PROVIDER',
  TEMPLATE_ENGINE: 'TEMPLATE_ENGINE',
  TEMPLATE_REPOSITORY: 'TEMPLATE_REPOSITORY',
} as const;

export type InjectionTokens =
  (typeof INJECTION_TOKENS)[keyof typeof INJECTION_TOKENS];
